image:
  file: .gitpod.dockerfile
tasks:
  - before: |
      export PATH=$FLUTTER_HOME/bin:$ANDROID_HOME/bin:$ANDROID_HOME/platform-tools:$PATH
      mkdir -p /home/gitpod/.android
      touch /home/gitpod/.android/repositories.cfg
init: |
    echo "Installing Flutter SDK..."
command: |
  flutter pub upgrade
  echo "Ready to go!"
  flutter doctor
vscode:
  extensions:
    - Dart-Code.dart-code
    - Dart-Code.flutter
